### ISSUE TITLE
RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by jingxinxin** [maichong/labrador#47]
我运行了 labrador watch
出现了下面的报错
......
......
build xml src/pages/todo/todo.xml -> dist/pages/todo/todo.wxml
[xmldom warning]        attribute "wx:else" missed value!! "wx:else" instead2!! 
@#[line:17,col:3]
RangeError: Maximum call stack size exceeded
    at /usr/local/lib/node_modules/labrador-cli/lib/build-less.js:41:33
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at build (/usr/local/lib/node_modules/labrador-cli/lib/build-less.js:29:15)
    at /usr/local/lib/node_modules/labrador-cli/lib/build-less.js:55:12
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at build (/usr/local/lib/node_modules/labrador-cli/lib/build-less.js:29:15)
    at /usr/local/lib/node_modules/labrador-cli/lib/build-less.js:55:12
    at RegExp.[Symbol.replace] (native)
RangeError: Maximum call stack size exceeded
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at build (/usr/local/lib/node_modules/labrador-cli/lib/build-less.js:29:15)
    at /usr/local/lib/node_modules/labrador-cli/lib/build-less.js:55:12
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
    at build (/usr/local/lib/node_modules/labrador-cli/lib/build-less.js:29:15)
    at /usr/local/lib/node_modules/labrador-cli/lib/build-less.js:55:12
    at RegExp.[Symbol.replace] (native)
    at String.replace (native)
build js src/pages/ui/index.js -> dist/pages/ui/index.js
......
.....

不知道是我代码问题还是什么

**Comment by jingxinxin** [comment]
已经解决
